# Classification

**Google** defines word <i>classify</i> as **`arrange (a group of people or things) in classes or categories according to shared qualities or characteristics`**. 
In Machine Learning, Classification is the process to train the model which can predict the class(group) in the given information belongs. Classification is a type of **`supervised learning`**, meaning that the training data includes both the input features and the corresponding labels, guiding the model to learn the correct associations.

**Examples**
1. A Loan officer in a bank have to decide whether the applicant is <strong>"Safe"</strong> or <strong>"risky"</strong>
2. A OCR(Optical Character Recognition) software to determine which is the given alphabet.

* **Binary Classification**: Example 1 is an instance of binary classification, where the prediction can only be one of two possible classes (e.g., "Safe" or "Risky"). 
* **Multi-Class Classification**: Example 2 illustrates multi-class classification, where the prediction can be one of many classes.

Data classification is a two-step process, consisting of a learning step (where a classification model is constructed) and a classification step (where the model is used to predict class labels for given data). The First image below shows the learning step and second image shows the classification step.

![Training Step in Classification](images/classification_training.JPG)

![Prediction Step in Classification](images/classification_prediction.JPG)

## Classification Using Decision Tree

Decision Tree is a supervised machine learning algorithm. A decision tree is a flowchart-like tree structure, where each internal node (non-leaf node) denotes a test on a feature, each branch represents the decision taken on the basis of the test and each leaf node denotes the output.

Decision tree can perform both regression and classification tasks. Decision Tree is one of the simplest yet effective machine learning algorithm. As we will see `Decision Trees` are intuitive and their decisions are easy to interpret.

| Outlook  | Temperature | Humidity | Wind   | PlayTennis |
|----------|-------------|----------|--------|------------|
| Sunny    | Hot         | High     | Weak   | No         |
| Sunny    | Hot         | High     | Strong | No         |
| Overcast | Hot         | High     | Weak   | Yes        |
| Rain     | Mild        | High     | Weak   | Yes        |
| Rain     | Cool        | Normal   | Weak   | Yes        |
| Rain     | Cool        | Normal   | Strong | No         |
| Overcast | Cool        | Normal   | Strong | Yes        |
| Sunny    | Mild        | High     | Weak   | No         |
| Sunny    | Cool        | Normal   | Weak   | Yes        |
| Rain     | Mild        | Normal   | Weak   | Yes        |
| Sunny    | Mild        | Normal   | Strong | Yes        |
| Overcast | Mild        | High     | Strong | Yes        |
| Overcast | Hot         | Normal   | Weak   | Yes        |
| Rain     | Mild        | High     | Strong | No         |

A Representation of the Decision Tree Algorithm is shown in figure below

![Decision Tree Example: Play Tennis](images/decision_tree_example.png)

Image Source: https://miro.medium.com/v2/resize:fit:640/format:webp/1*1_I2S5xiW49_A0kP7mgQDQ.png

**Root Node**: It is the topmost node in the tree, which represent the complete dataset. Also, we can say it is the starting point of the decision-making process.

**Decision/Internal Node**: Decision nodes are nothing but the result in the splitting of data into multiple data segments and main goal is to have the children nodes with maximum homogeneity or purity( means of the same kind).

**Leaf/Terminal Node**: This node represent the data section having highest homogeneity (means of the same kind).

### ID3 Algorithm

During the late 1970s and early 1980s, J. Ross Quinlan, a researcher in machine learning developed a decision tree algorithm known as **ID3** (Iterative Dichotomiser 3). In this algorithm, we use an attribute selection method to compute a heuristic for selecting the attribute that "best" discriminates the given tuples according to class.

It is a greedy algorithm that builds a decision tree by recursively partitioning the data set into smaller and smaller subsets until all data points in each subset belong to the same class. It employs a top-down approach, recursively selecting features to split the dataset

#### Attribute Selection Measures

An **attribute selection measure** is a heuristic for selecting the splitting criterion that `best` separates a given data partition, $D$, of class-labeled training tuples into individual classes. If we were to split $D$ into smaller partitions according to the outcomes of the splitting criterion, ideally each partition would be pure (i.e., all the tuples that fall into a given partition would belong to the same class). Conceptually, the `best` splitting criterion is the one that most closely results in such a scenario. Attribute selection measures are also known as splitting rules because they determine how the tuples at a given node are to be split. Entropy, Information Gain, Gini Index are some of the popular attribute selection measure

##### Entropy
In Machine Learning, entropy measures the level of disorder or uncertainty in a given dataset or system. It is a metric that quantifies the amount of information in a dataset

$$Entropy(D) = -\sum_{i=1}^mp_ilog_2(p_i)$$
Entropy is also sometime represented as 

$$Info(D)=-\sum_{i=1}^mp_ilog_2(p_i)$$
##### Information Gain
Information Gain I(A) tells us how much uncertainty in D was reduced after splitting set $D$ on attribute A.

$$Info_{A}(D)=\frac{\left|D_j\right|}{\left|D\right|}*Info(D_j)$$


Information gain is defined as the difference between the original information requirement (i.e., based on just the proportion of classes) and the new requirement (i.e.obtained after partitioning on A). That is,

$$Gain(A)=Info(D)-Info_A(D)$$ 

In other words, $Gain(A)$ tells us how much would be gained by branching on $A$. It is the expected reduction in the information requirement caused by knowing the value of $A$. The attribute $A$ with the highest information gain, Gain(A), is chosen as the splitting
attribute at node $N$.

Steps to making Decision Tree
1. Take the Entire dataset as an input.
2. Calculate the Entropy of the target variable, As well as the predictor attributes
3. Calculate the information gain of all attributes.
4. Choose the attribute with the highest information gain as the Root Node
5. Repeat the same procedure on every branch until the decision node of each branch is finalized.

We will use a popular Play Tennis dataset to understand the Decision Tree Algorithm. Here we classify if we should play tennis or not based on various weather features.

| Outlook  | Temperature | Humidity | Wind   | PlayTennis |
|----------|-------------|----------|--------|------------|
| Sunny    | Hot         | High     | Weak   | No         |
| Sunny    | Hot         | High     | Strong | No         |
| Overcast | Hot         | High     | Weak   | Yes        |
| Rain     | Mild        | High     | Weak   | Yes        |
| Rain     | Cool        | Normal   | Weak   | Yes        |
| Rain     | Cool        | Normal   | Strong | No         |
| Overcast | Cool        | Normal   | Strong | Yes        |
| Sunny    | Mild        | High     | Weak   | No         |
| Sunny    | Cool        | Normal   | Weak   | Yes        |
| Rain     | Mild        | Normal   | Weak   | Yes        |
| Sunny    | Mild        | Normal   | Strong | Yes        |
| Overcast | Mild        | High     | Strong | Yes        |
| Overcast | Hot         | Normal   | Weak   | Yes        |
| Rain     | Mild        | High     | Strong | No         |

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
df = pd.read_csv("datasets/play_tennis.csv")

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

Let us use the ID3 Algorithm to find the Root, Internal and Leaf Nodes

##### Step 1: Calculate the Entropy of the Entire Dataset

$$Entropy(D) = -\left( \frac{9}{14} \log_2 \frac{9}{14} + \frac{5}{14} \log_2 \frac{5}{14} \right) \approx 0.94$$

In [5]:
# Function to calculate entropy
def compute_entropy(target_col):
    elements, counts = np.unique(target_col, return_counts=True)
    entropy = np.sum([(-counts[i]/np.sum(counts)) * math.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    return entropy

In [6]:
np.unique(df['outlook'], return_counts=True)

(array(['Overcast', 'Rain', 'Sunny'], dtype=object),
 array([4, 5, 5], dtype=int64))

In [7]:
df['outlook'].value_counts()

outlook
Sunny       5
Rain        5
Overcast    4
Name: count, dtype: int64

In [8]:
# Calculate the entropy of the entire dataset
total_entropy = compute_entropy(df['play'])
print(f'Entropy of the entire dataset: {total_entropy:.3f}')

Entropy of the entire dataset: 0.940

**1. Outlook:**

- Sunny:

  $$
  Entropy(Sunny) = -\left( \frac{2}{5} \log_2 \frac{2}{5} + \frac{3}{5} \log_2 \frac{3}{5} \right) \approx 0.971
  $$

- Overcast:

  $$
  Entropy(Overcast) = -\left( \frac{4}{4} \log_2 \frac{4}{4} \right) = 0
  $$

- Rain:

$$
  Entropy(Rain) = -\left( \frac{3}{5} \log_2 \frac{3}{5} + \frac{2}{5} \log_2 \frac{2}{5} \right) \approx 0.971
$$

Calculate the weighted average entropy for Outlook:

$$
Entropy(Outlook) = \frac{5}{14} \cdot 0.971 + \frac{4}{14} \cdot 0 + \frac{5}{14} \cdot 0.971 \approx 0.693
$$

#### Step 3: Calculate the Information Gain for Each Feature

**1. Outlook:**

$$
IG(Outlook) = 0.94 - 0.693 = 0.247
$$

Similarly, Calculate the Information Gain for each of the features, and the feature with the highest value of Information Gain is chosen as the root node.

If we continue the calculation for each feature we will get the following result.

* Information Gain for outlook: 0.247
* Information Gain for temp: 0.029
* Information Gain for humidity: 0.152
* Information Gain for wind: 0.048

Since the Information Gain for outlook is maximum we will take `outlook` as the root node. The feature `outlook` has three values `Sunny`, `Overcast`, and `Rain`. Since `Overcast` has only `Yes` as the target value we can say if $outlook==Overcast$ then play tennis = Yes, so we can leave it as a leaf node. However, for `Sunny` and `Rain` there are both Yes and No in target column so, we have to continue process   

![outlook as Root Node](images/dt_step1.png)

Further Calculation is Available in the Following Document
1. [Decision Tree Calculation Example]('Decision%20Tree%20ID3%20worked%20example.pdf')

## Simple Implementation

In [9]:
# Function to calculate information gain
def info_gain(df, split_attribute_name, target_name="play"):
    # Calculate the entropy of the total dataset
    total_entropy = compute_entropy(df[target_name])
    
    # Calculate the values and counts for the split attribute
    vals, counts = np.unique(df[split_attribute_name], return_counts=True)
    
    # Calculate the weighted entropy
    weighted_entropy = np.sum([(counts[i]/np.sum(counts)) * compute_entropy(df.where(df[split_attribute_name]==vals[i]).dropna()[target_name]) for i in range(len(vals))])
    
    # Calculate the information gain
    information_gain = total_entropy - weighted_entropy
    return information_gain

In [10]:
# Calculate the information gain for each feature
features = ['outlook', 'temp', 'humidity', 'wind']
info_gains = {feature: info_gain(df, feature) for feature in features}

In [11]:
# Print the information gains
for feature in features:
    print(f'Information Gain for {feature}: {info_gains[feature]:.3f}')

Information Gain for outlook: 0.247
Information Gain for temp: 0.029
Information Gain for humidity: 0.152
Information Gain for wind: 0.048

In [12]:
# Determine the feature with the highest information gain
best_feature = max(info_gains, key=info_gains.get)
print(f'Best feature to split on: {best_feature}')

Best feature to split on: outlook

In [13]:
df1 = df[df['outlook']=='Sunny']
df2 = df[df['outlook']=='Rain']

In [14]:
df1

    day outlook  temp humidity    wind play
0    D1   Sunny   Hot     High    Weak   No
1    D2   Sunny   Hot     High  Strong   No
7    D8   Sunny  Mild     High    Weak   No
8    D9   Sunny  Cool   Normal    Weak  Yes
10  D11   Sunny  Mild   Normal  Strong  Yes

In [15]:
df2

    day outlook  temp humidity    wind play
3    D4    Rain  Mild     High    Weak  Yes
4    D5    Rain  Cool   Normal    Weak  Yes
5    D6    Rain  Cool   Normal  Strong   No
9   D10    Rain  Mild   Normal    Weak  Yes
13  D14    Rain  Mild     High  Strong   No

In [15]:
all_dfs = [df1,df2]
for index, item in enumerate(all_dfs):
    print(f"For datafrmae_{index+1}")
    info_gains = {feature: info_gain(item, feature) for feature in features}
    # Print the information gains
    for feature in features:
        print(f'Information Gain for {feature}: {info_gains[feature]:.3f}')
    # Determine the feature with the highest information gain
    best_feature = max(info_gains, key=info_gains.get)
    print(f'Best feature to split on: {best_feature}')

For datafrmae_1
Information Gain for outlook: 0.000
Information Gain for temp: 0.571
Information Gain for humidity: 0.971
Information Gain for wind: 0.020
Best feature to split on: humidity
For datafrmae_2
Information Gain for outlook: 0.000
Information Gain for temp: 0.020
Information Gain for humidity: 0.020
Information Gain for wind: 0.971
Best feature to split on: wind

From the output of the code above we can see that for node where $outlook==`Sunny`$ the maximum value of Information Gain is for the feature humidity so the next node will be humidity.

![Play Tennis Final Decision Tree](images/Play-Tennis-decision-tree-example.png)