In [10]:
import pandas as pd
import statsmodels.api as sm

In [2]:
df = pd.read_csv("datasets/lifesat.csv")

In [3]:
df.head()

   Country  GDP per capita (USD)  Life satisfaction
0   Russia          26456.387938                5.8
1   Greece          27287.083401                5.4
2   Turkey          28384.987785                5.5
3   Latvia          29932.493910                5.9
4  Hungary          31007.768407                5.6

In [4]:
df = df.drop(columns=['Country'])

In [7]:
df = df.rename(columns={
    'GDP per capita (USD)':'pci',
    'Life satisfaction': 'life_sat'
})

In [8]:
df.head()

            pci  life_sat
0  26456.387938       5.8
1  27287.083401       5.4
2  28384.987785       5.5
3  29932.493910       5.9
4  31007.768407       5.6

In [11]:
X = df['pci']
X = sm.add_constant(X)  # Adds the intercept term
Y = df['life_sat']

In [12]:
model = sm.OLS(Y, X)       # Ordinary Least Squares
results = model.fit()

In [13]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               life_sat   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.716
Method:                 Least Squares   F-statistic:                     66.66
Date:                Sun, 03 Aug 2025   Prob (F-statistic):           1.62e-08
Time:                        05:08:17   Log-Likelihood:                -13.051
No. Observations:                  27   AIC:                             30.10
Df Residuals:                      25   BIC:                             32.69
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.7490      0.354     10.593      0.000       3.020       4.478
pci         6.779e-05    8.3e-06      8.165      0.000    5.07e-05    8.49e-05
==============================================================================
Omnibus:                        0.438   Durbin-Watson:                   1.924
Prob(Omnibus):                  0.804   Jarque-Bera (JB):                0.059
Skew:                           0.111   Prob(JB):                        0.971
Kurtosis:                       3.049   Cond. No.                     1.92e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.92e+05. This might indicate that there are
strong multicollinearity or other numerical problems.