In [1]:
import pandas as pd
import statsmodels.api as sm

In [2]:
!pip install statsmodels

Requirement already satisfied: statsmodels in d:\broadway\datascience\venv\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in d:\broadway\datascience\venv\lib\site-packages (from statsmodels) (2.3.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in d:\broadway\datascience\venv\lib\site-packages (from statsmodels) (1.16.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in d:\broadway\datascience\venv\lib\site-packages (from statsmodels) (2.3.1)
Requirement already satisfied: patsy>=0.5.6 in d:\broadway\datascience\venv\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in d:\broadway\datascience\venv\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\broadway\datascience\venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\broadway\datascience\venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\broadway\datascience\venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in d:\broadway\datascience\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
df = pd.read_csv("datasets/lifesat.csv")

In [4]:
df.head()

   Country  GDP per capita (USD)  Life satisfaction
0   Russia          26456.387938                5.8
1   Greece          27287.083401                5.4
2   Turkey          28384.987785                5.5
3   Latvia          29932.493910                5.9
4  Hungary          31007.768407                5.6

In [5]:
df = df.drop(columns=['Country'])

In [6]:
df = df.rename(columns={
    "GDP per capita (USD)":"pci",
    "Life satisfaction":"life_sat"
})

In [7]:
df.head()

            pci  life_sat
0  26456.387938       5.8
1  27287.083401       5.4
2  28384.987785       5.5
3  29932.493910       5.9
4  31007.768407       5.6

In [8]:
X = df['pci']

In [9]:
X = sm.add_constant(X)

In [10]:
Y = df['life_sat']

In [11]:
model = sm.OLS(Y,X)

In [13]:
result = model.fit()

In [16]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               life_sat   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.716
Method:                 Least Squares   F-statistic:                     66.66
Date:                Sun, 03 Aug 2025   Prob (F-statistic):           1.62e-08
Time:                        08:25:04   Log-Likelihood:                -13.051
No. Observations:                  27   AIC:                             30.10
Df Residuals:                      25   BIC:                             32.69
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.7490      0.354     10.593      0.000       3.020       4.478
pci         6.779e-05    8.3e-06      8.165      0.000    5.07e-05    8.49e-05
==============================================================================
Omnibus:                        0.438   Durbin-Watson:                   1.924
Prob(Omnibus):                  0.804   Jarque-Bera (JB):                0.059
Skew:                           0.111   Prob(JB):                        0.971
Kurtosis:                       3.049   Cond. No.                     1.92e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.92e+05. This might indicate that there are
strong multicollinearity or other numerical problems.